# Generated by Django 2.2.2 on 2019-06-09 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('helprequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.Skill'),
        ),
    ]
